# Vexy SVGO Clippy Configuration
# this_file: clippy.toml

# Maximum allowed cyclomatic complexity
cognitive-complexity-threshold = 30

# Maximum number of lines allowed in a single function
too-many-lines-threshold = 100

# Maximum number of arguments allowed in a function
too-many-arguments-threshold = 7

# Maximum size of types in bytes
type-complexity-threshold = 250

# Enforce documentation on public items
missing-docs-in-crate-items = true

# Disallowed types
disallowed-types = [
    # Use specific error types instead of generic strings
    { path = "std::boxed::Box<dyn std::error::Error>", reason = "Use specific error types" },
]

# Configure MSRV (Minimum Supported Rust Version)
msrv = "1.70.0"

# Warn on common issues
warn-on-all-wildcard-imports = true
enum-variant-name-threshold = 3
single-char-binding-names-threshold = 3

# Enforced naming conventions  
enforced-import-renames = [
    { path = "std::collections::HashMap", rename = "HashMap" },
    { path = "std::collections::HashSet", rename = "HashSet" },
]

# Allow certain patterns that are common in this codebase
allowed-wildcard-imports = ["vexy_svgo_core::ast::*"]