site_name: Vexy SVGO
site_url: https://vexyart.github.io/vexy-svgo
repo_url: https://github.com/vexyart/vexy-svgo
repo_name: vexyart/vexy-svgo
edit_uri: blob/main/docs_src/  # "Edit on GitHub" links

# Where MkDocs should read & write
docs_dir: docs_src      # <-- new source tree
site_dir: docs          # <-- rendered output; GitHub Pages already uses this

theme:
  name: material
  palette:
    scheme: slate       # dark-mode out of the box
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.tabs.link
  favicon: assets/favicon.ico
  logo: assets/favicon.ico

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - search
  - awesome-nav               # auto-build nav tree
  - mkdocs-nav-weight:        # order by front-matter nav_weight
      section_renamed: false

extra_css:
  - assets/css/main.css       # static assets copied verbatim
extra_javascript:
  - assets/js/svgo-optimizer.js
  - assets/js/theme.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vexyart/vexy-svgo