# Vexy SVGO Rust Formatting Configuration
# this_file: rustfmt.toml

# Use verbose diffs
verbose = true

# Version gate formatting
edition = "2021"

# Maximum line width
max_width = 120

# Use spaces for indentation
hard_tabs = false
tab_spaces = 4

# Function and method calls
use_small_heuristics = "Default"
fn_call_width = 100

# Control flow
control_brace_style = "AlwaysSameLine"

# Imports
imports_granularity = "Module"
imports_layout = "Mixed"
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"

# Comments
comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true
normalize_doc_attributes = true

# Chains
chain_width = 100
single_line_if_else_max_width = 50

# Enums and structs
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

# Match statements
match_block_trailing_comma = true
match_arm_blocks = true

# Misc
use_field_init_shorthand = true
use_try_shorthand = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true

# Error handling
error_on_line_overflow = false
error_on_unformatted = false

# Stability
unstable_features = true