---
author:
  name: Fontlab Ltd. dba Vexy Co
  url: https://vexy.art/
aux_links:
  View on GitHub:
    - https://github.com/vexyart/vexy-svgo
back_to_top: true
back_to_top_text: Back to top
baseurl: /vexy-svgo
collections:
  pages:
    output: true
    permalink: /:name/
color_scheme: dark
description: SVG optimizer in Rust
enable_copy_code_button: true
exclude:
  - _build.sh
  - _serve.sh
  - '*.erb'
  - '*.gemspec'
  - '*.orig'
  - '*.sh'
  - '**/gems/jekyll-*/lib/site_template/_posts/*'
  - '**/site_template/**/*'
  - dev/**/*
  - Gemfile
  - Gemfile.lock
  - internal/**/*
  - node_modules/
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
# Footer
footer_content: Copyright &copy; 2025 Vexy Co. MIT License.
# Assets
github:
  repository_url: https://github.com/vexyart/vexy-svgo
include:
  - assets/js/
  - assets/css/main.css
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/vexyart/vexy-svgo
  - title: SVGO Reference
    url: https://github.com/svg/svgo
# Navigation
nav_sort: case_insensitive
# GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs
# Build settings
repository: vexyart/vexy-svgo
sass:
  sass_dir: _sass
  style: compressed
search:
  button: false
  heading_level: 2
  preview_words_after: 10
  preview_words_before: 5
  previews: 3
  rel_url: true
  tokenizer_separator: /[\s/]+/
# Search settings
search_enabled: true
# Site settings
social:
  - icon: github
    name: GitHub
    url: https://github.com/vexyart/vexy-svgo
title: Vexy SVGO
url: https://vexyart.github.io/vexy-svgo
