# this_file: .github/workflows/dependency-cache.yml

name: Dependency Cache

on:
  schedule:
    # Run weekly to keep caches fresh
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  cache-dependencies:
    name: Cache Dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      
      - name: Configure cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          key: deps-${{ matrix.os }}
          cache-targets: false
          cache-on-failure: true
      
      - name: Download dependencies
        run: cargo fetch
      
      - name: Build dependencies only
        run: |
          cargo build --release --workspace
          cargo test --release --workspace --no-run
      
      - name: Save dependency build timing
        run: |
          echo "Dependencies cached at: $(date)" > target/cache-timestamp.txt