# this_file: .github/workflows/docs.yml

name: build-and-publish-docs
on:
  push:
    branches: [main]
    paths:
      - "docs_src/**"
      - "mkdocs.yml"
      - "requirements.txt"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs toolchain
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean docs directory
        run: rm -rf docs/*

      - name: Build MkDocs site into /docs
        run: mkdocs build --config-file mkdocs.yml

      - name: Add .nojekyll file
        run: touch docs/.nojekyll

      - name: Commit & push generated docs
        uses: EndBug/add-and-commit@v9      # lightweight "commit back" action
        with:
          add: "docs"
          message: "ci(docs): auto-build with MkDocs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}